#
# MADE BY: AnonymouslyFast (Caleb)
#
# Below is the configuration for the bot
# If the '' is empty it need a input
# please do not change anything unless needed
#


bot-token: ''
minecraft-to-discord-channel-id: ''
minecraft-logs-channel-id: ''