#
# MADE BY: AnonymouslyFast (Caleb)
#
# Below is the configuration for the bot
# If the '' is empty it need a input
# please do not change anything unless needed
#

# Discord

bot-token: ''
minecraft-to-discord-channel-id: ''
minecraft-logs-channel-id: ''
discord-verification-channel-id: ''
discord-verified-role-id: ''
guild-id: ''

# DataBase
db-username: ''
db-password: ''
# The Data base template is:
#  jdbc:sqlserver://ServerName:Port;databaseName=;user=username;password=password;
db-url: ''

